React native setup
aryonna-rice/comp-523-dreamscape pull request #13
Opened 2023-11-30 14:42 UTC by karengpalomo

React native application for caregivers was set up. This is intended to be used on mobile.

2023-11-30 19:14 UTC, imharris2702 requested changes
Looks like a .DS_Store got added in on accident, needs to be removed

2023-11-30 19:14 UTC, imharris2702 commented on .DS_Store
Don't think we want to include this file, can we remove it from the branch?

2023-12-01 17:21 UTC, karengpalomo commented on .DS_Store
Yeah i can go ahead and delete it so that it's removed from the branch altogether

2023-12-01 18:57 UTC, imharris2702 approved these changes
looks good to me

2023-12-02 16:20 UTC, merged